### PR TITLE
Add changes from my fork ( highlight-actions.nvim )

### PR DESCRIPTION
**Pull request by iguanacucumber**
Originally i did not made a PR, because i changed quite some things and it would seem weird to make a PR to change like half the plugin with breaking changes. But if youre fine with it, i'm more than happy to make this PR. I'm going to sum up the changes i've made:
- Added Pasted action
- Renamed lhs to keymap & map to cmd for better clarity towards end users
- Highlight groups are created automatically
- fg & bg can be applied to individual actions
- Allow for incomplete definition ( see line 130 )
- Added the ability to disable actions
- Added the ability to create actions

### CODE REVIEW

**Comment by tzachar** [comment]
Thanks for backporting your changes.
I think that a more general approach would be more beneficial; We can setup a more general config where the user specifies the keymaps we should highjack and we can highjack them in a more generic way. This way we wont need to manually re-implement functionality by hand (like pasting, etc).
This is more inline with the plugin as it is written now.

wdyt?

**Comment by iguanacucumber** [comment]
Looking for changed text in the buffer after a keymap is pressed i believe is the way to go ( I mostly made my fork to learn lua and the nvim API, that's why it's not the best solution ). For it to be perfect we would need to listen on the keymaps, and not make new ones, like a keylogger would do ( though i don't know if we can even listen to keypresses in the background with the API )

**Comment by tzachar** [comment]
You dont need a keylogger....
I was thinking something like asking the user to config which keymaps we should hijack.
We then use `nvim_get_keymap` and `nvim_buf_get_keymap` to inspect the keymaps, either recording the `rhs` or the callback invoked.
We then replace the keymap callback with our own callback, where we perform the highlight logic and call the original keymap (call `rhs` using `feedkeys` or the callback directly).

**Comment by tzachar** [comment]
Hi @iguanacucumber 
pls check out this PR: #26

**Comment by iguanacucumber** [comment]
works really well ! (I just made some slight improvements, nothing too fancy)

**Comment by tzachar** [comment]
So, I think we should close this PR, and merge #26 
I'll update the README, if you have anything to add lets move the conversation there.
10x.

**Pull request closed without merging**
