### PR TITLE
♻️refactor(`vim.highlight`): Is going to be deprecated. Let's use `vim.hl` instead.

### PR DESCRIPTION
**Pull request by Zeioth**

### CODE REVIEW

**Comment by tzachar** [comment]
In which version was it first introduced?
If this is recent, not prior to 0.10, lets maintain backwards compatibility by using `(vim.hl or vim.highlight)`.

**Comment by Zeioth** [comment]
the old one was deprecated in nvim 0.9, the new one kntroduced in 0.10

**Comment by Frestein** [comment]
image
Good job.
NVIM v0.10.2 Build type: RelWithDebInfo LuaJIT 2.1.1727870382

**Comment by rperryng** [comment]
I also just ran into this problem

```
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713484068
```

it looks like `vim.hl` was only introduced to `neovim` ~3 weeks ago in [this PR](https://github.com/neovim/neovim/pull/30840), and the latest stable release for `neovim` is [`0.10.2`](https://github.com/neovim/neovim/releases/tag/v0.10.2) which is older than the change.

worth noting that the PR introducing the rename says:

> This is not a breaking change until 2.0 (or maybe never).

**Pull request merged**
