### PR TITLE
🐛fix: vim.hl is only available starting nvim 0.11

### PR DESCRIPTION
**Pull request by Zeioth**
Apologies for the mistake. Here is the fix.

### CODE REVIEW

**Comment by Zeioth** [comment]
Also, 1ea1c79372d7d93c88fd97543880927b7635e3d2 is the last working commit on my end. The commits after that one break `p` paste.

**Comment by Frestein** [comment]
You can try using `vim.hl = vim.hl or vim.highlight`. This is a cleaner solution.

**Comment by tzachar** [comment]
fix with `(vim.hl or vim.highlight)`

**Comment by tzachar** [comment]
@Zeioth 
> Also, [1ea1c79](https://github.com/tzachar/highlight-undo.nvim/commit/1ea1c79372d7d93c88fd97543880927b7635e3d2) is the last working commit on my end. The commits after that one break `p` paste.

Do you have `p` bound to something while using some other plugin?
Can you provide some more info?
This is usually solved by loading this plugin last.

**Comment by Zeioth** [comment]
Indeed the issue was project.nvim was loading before `highlight-undo.nvim`, and that was causing the hijack to fail (causing `p` to open project.nvim instead of pasting).

I see it risky for little gain. `NormalNvim` is going to stick with https://github.com/tzachar/highlight-undo.nvim/commit/1ea1c79372d7d93c88fd97543880927b7635e3d2 for now for the next reasons:

* **New hijack method**: Can cause unpredictible results in a user decides to not load this plugin at top.
* **New config is boilerplate**: And fields don't default to any value, so you are force to specify them all.

I'll revisit this in the future.

**Comment by Zeioth** [comment]
Indeed the issue was project.nvim was loading before highlight-undo.nvim, and that was causing the hijack to fail (causing p to open project.nvim instead of pasting).

I see it risky for little gain. NormalNvim is going to stick with https://github.com/tzachar/highlight-undo.nvim/commit/1ea1c79372d7d93c88fd97543880927b7635e3d2 for now for the next reasons:

* **New hijack method**: Can cause unpredictible results in a user decides to not load this plugin at top.
* **New config is boilerplate**: And fields don't default to any value, so you are force to specify them all.

I'll revisit this in the future.

**Comment by tzachar** [comment]
@Zeioth What would you expect to happen? when you have two plugins which map the same key, the last one loaded will take precedence... I dont see how `p` can `paste` in your scenario, as you say that `p` already opens `project.nvim`. 
Anyway, I would appreciate if you can elaborate on you second point. As you can provide no config at all, I dont understand your point.
10x.

**Pull request closed without merging**
